server:
  port: 9000
spring:
  application:
    name: service-gateway-v2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8841
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: path_route_2service
        predicates:
        - Path=/auth/**
#        - Method=POST
#        uri: http://localhost:8082
        uri: lb://service-auth
        filters:
        - StripPrefix=1
      - id: biz-monitor
        predicates:
        - Path=/biz-monitor/**
        uri: lb://biz-monitor
        filters:
        - StripPrefix=1
  redis:
    host: localhost
    port: 6379
#  zipkin:
#    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1
    zuul:
      enabled: false
  zipkin:
    sender:
      type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true

#      - id: query_route_2163
#        predicates:
#        - Query=userid, \d+
#        uri: http://163.com
#        order: 2
#      - id: time_route_2baidu
#        predicates:
##        - After=2019-12-25T10:00:00+08:00:00[Asia/Shanghai]
##        - Before=2019-12-25T10:00:00+08:00:00[Asia/Shanghai]
#        - Between=2019-12-25T10:00:00+08:00:00[Asia/Shanghai],2029-12-25T10:00:00+08:00:00[Asia/Shanghai]
#        uri: http://baidu.com
#        order: 1

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
