
server:
  port: 8090
spring:
  application:
    name: cloud-config
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8841,localhost:8842,localhost:8843
    config:
      server:
        native:
          search-locations: classpath:/config
          #git:
          #  uri: https://github.com/cpaqyx/fastwaveCloudCourse
          # uri: https://gitee.com/cpaqyx/fastwaveCloudCourse.git
          #username:
          #password:
          #search-paths: config
  profiles:
    active: native