server:
  port: 8082

spring:
  application:
    name: services-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8841,localhost:8842,localhost:8843
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#logging:
#  level:
#    root: debug