server:
  port: 8082

spring:
  application:
    name: services-auth
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      web-context-unify: false # 调用链树展开
  # 解决报错：Relying upon circular references is discouraged and they are prohibited by default.
  # Update your application to remove the dependency cycle between beans. As a last resort,
  # it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

  main:
    allow-circular-references: true