server:
  port: 8082

spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8841
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#logging:
#  level:
#    root: debug