server:
  port: 9000
spring:
  application:
    name: service-gateway-v2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8841
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    root: debug