hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 超时时间，默认1000ms，
            # hystrix超时时间的计算： (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout
            timeoutInMilliseconds: 1000
      circuitBreaker:
        #熔断器在整个统计时间内是否开启的阀值，默认20。也就是10秒钟内至少请求20次，熔断器才发挥起作用
        requestVolumeThreshold: 10
        #熔断器默认工作时间,默认:5秒.熔断器中断请求5秒后会关闭重试,如果请求仍然失败,继续打开熔断器5秒,如此循环
        sleepWindowInMilliseconds: 10000
        #当出错率超过50%后熔断器启动
        errorThresholdPercentage: 50

feign:
  hystrix:
    enabled: true

custom:
  pic:
    path: e:\uploadfiles
